apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: angular-prod 
spec: 
  selector: 
    matchLabels: 
      app: angular-prod 
  replicas: 1 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: angular-prod 
    spec: 
      containers: 
      - name: angular-prod 
        image: docker.io/tusharja2986/angular-app:#{Build.BuildId}#
        ports: 
        - containerPort: 80 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: angular-prod 
spec: 
  selector: 
    app: angular-prod 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
  type: LoadBalancer 
  #type: NodePort
